### ISSUE TITLE
Plans or projects for the axios docs?

### ISSUE THREAD

**Issue by giacomocerquone** [axios/axios-docs#1]
Hi everyone, I spent some of my free time creating a documentation website with docusaurus for axios which I still have to publish and I'm about to buy a domain.
So in order to understand if you're going to do the same, I'd like to ask you, what are your plans? Do you have something like that in mind?

Thanks

**Comment by jasonsaayman** [comment]
Hi @giacomocerquone,

We are planning to do the same. I have something like that in mind. I will reply on your mail.

Thanks

**Comment by jasonsaayman** [comment]
Hi

The docs are being updated today with the new source.

Thanks
