### ISSUE TITLE
Some sponsor logos are grayed out while others are not

### ISSUE THREAD

**Issue by fcamgz** [axios/axios-docs#159]
**Is your feature request related to a problem? Please describe.**
On the Axios website homepage, there is a number of sponsor logos are grayed out when they are not hovered over. You can see them when you click on the right arrow to go to the end of the sponsor list. It might be a good idea to add that hover transition on all the sponsors to keep the design aligned. 

**Describe the solution you'd like**
All the sponsor logos have a hover transition effect. 

**Describe alternatives you've considered**
Removing the hover effect from all the sponsor logos.

**Additional context**
when not hovered:
![homepage-sponsors](https://github.com/axios/axios-docs/assets/62274639/e9d3818d-ac4c-449a-a601-708f400b9115)
when hovered: 
![image](https://github.com/axios/axios-docs/assets/62274639/71e876a4-1332-48e7-aefa-b5b505c201ab)

**Comment by DigitalBrainJS** [comment]
That is expected behavior. The transparency of the badge indicates the sponsor's inactivity. When a certain threshold is reached, the badge will be completely removed from the list.
