### ISSUE TITLE
https://axios-http.com/ is down

### ISSUE THREAD

**Issue by KyryloKaralyus** [axios/axios-docs#25]
**Describe the bug**
Website seems to be waay down.

**To Reproduce**
1. Go to 'https://axios-http.com/'
2. Witness nothing '....'

**Expected behavior**
1. See website

**Screenshots**
![image](https://user-images.githubusercontent.com/61317958/115958621-d49c3980-a510-11eb-8f13-e4df550b9614.png)

**Desktop (please complete the following information):**
 - OS: Debian 10,  android as well;
 - Browser both firefox and brave

**Comment by codemaster138** [comment]
Yeah, same here... (Chrome Dev 91)

@jasonsaayman Maybe check netlify?

**Comment by jasonsaayman** [comment]
My fault, fixed now, the domain registrar did not auto charge me...

**Comment by codemaster138** [comment]
@jasonsaayman  Still happening for me...

**Comment by jasonsaayman** [comment]
Mmm that's odd, seems up according to this https://www.isitdownrightnow.com/axios-http.com.html

**Comment by codemaster138** [comment]
@jasonsaayman It's up for me now, too. Maybe DNS propagation just took a bit longer in Europe...
