### ISSUE TITLE
Enable dark background on code blocks while in dark mode

### ISSUE THREAD

**Issue by swarup4741** [axios/axios-docs#35]
The text inside the code blocks become difficult to see properly while in dark mode .. making the background dark can increase the contrast ratio so that visibility enhances...

**Comment by jasonsaayman** [comment]
Hi @swarup4741 I agree, would you like to have a look at opening a pull request to facilitate this?

**Comment by swarup4741** [comment]
Yeah i would like to contribute

**Comment by jasonsaayman** [comment]
Closed by #36 thanks 😄
