### ISSUE TITLE
Merge documentation with additional docs written prior

### ISSUE THREAD

**Issue by jasonsaayman** [axios/axios-docs#5]
We need to look into addition this set of docs [https://github.com/chinesedfan/You-Dont-Know-Axios](https://github.com/chinesedfan/You-Dont-Know-Axios) to these docs/

**Comment by codemaster138** [comment]
I would be willing to do this, but we should first figure out the best way to incorporate this into the documentation. As it is not official axios documentation, I imagine we will have to keep it apart from the main docs in some way. @jasonsaayman I‘d be interested to hear your thoughts on how to do this

**Comment by jasonsaayman** [comment]
Yeah, I will have to have a look at it and see how we could do it in either a way that it makes sense in the context of the normal docs. I know the additional doc's are more in depth so maybe I can have a look and work on splitting it up into advanced and useful for the community at large.

**Comment by codemaster138** [comment]
@jasonsaayman Good idea! Keep me updated so that I can update the docs or translate the new content
