### ISSUE TITLE
Update docs regarding cancellation

### ISSUE THREAD

**Issue by 19shubham11** [axios/axios-docs#57]
I was searching about cancellable requests and was a bit confused about the existing docs here -> https://axios-http.com/docs/cancellation as they only talked about cancellable promises and I wanted to use `AbortController` 

Turns out, AbortController is of course supported since this PR was merged, but I had to dig a bit deep into the code to find that 😅  

- https://github.com/axios/axios/pull/3305

Maybe the docs should reflect the support for `AbortController` and reference to the relevant JS API ref for that!

**Comment by jasonsaayman** [comment]
Cool thanks, I will have to start being more insistent on docs being updated when support is added.

**Comment by jasonsaayman** [comment]
Done with #56
