### ISSUE TITLE
Show logos of bronze sponsors or better from opencollective

### ISSUE THREAD

**Issue by codemaster138** [axios/axios-docs#61]
**Is your feature request related to a problem? Please describe.**
The Axios OpenCollective states that backers with a contribution bronze or greater get their logo on the Axios Website. I was recently contacted by one of Axios' bronze backers about the fact that their logo is currently *not* on the site even though they have submitted a bronze sponsorship.

**Describe the solution you'd like**
The OpenCollective API allows including sponsor's logo into the website quite easily (https://api.opencollective.com/graphql/v2).

**Describe alternatives you've considered**
/

**Additional context**
This should be fairly simple, so I'll try to implement it myself as quickly as possible.

**Comment by jasonsaayman** [comment]
Thanks @codemaster138 can you also add the rest of the tiers?

**Comment by codemaster138** [comment]
@jasonsaayman Will do

**Comment by codemaster138** [comment]
I'll need an API key to test out my scripts. It would be great if you could invite me to the Axios organisation on OC (my email: jakesarjeant13@gmail.com)

**Comment by jasonsaayman** [comment]
@codemaster138 sorry for this being late but I have invited you :)

**Comment by jasonsaayman** [comment]
Done :)
