### ISSUE TITLE
GitHub Action for inert build

### ISSUE THREAD

**Issue by codemaster138** [axios/axios-docs#7]
I think it would be a good idea to add a github action to compile the site so that contributors don‘t have to download inert just to fix a type.

I have set this up before, and it‘s actually pretty easy, but if I remember correctly it can get a bit hairy to configure the environment for i18n, so I think it‘s best if I take care of this.

I will start working on a pull request ASAP, and I should be able to submit it by this evening.

**Comment by jasonsaayman** [comment]
Sure that makes sense, in the end though it should just have the final goal of being published to Netlify please.

**Comment by codemaster138** [comment]
@jasonsaayman Already finished my pull request, you can merge to close this issue
